export const createQuiz = async () => {
    try {
        // const newQuiz = await 
    } catch (error) {
        console.log(error, " craete quiz error");
    }
}